<?php
$menuName = 'Zend\Navigation\Default';
/** @var \MDBootstrap\View\Helper\Navigation\Navbar $menu */
$menu = $this->navigation($menuName)->MDBNavbar();
$menu->setClassToAItem('nav-link')
    ->setUlClass('navbar-nav mr-auto')
    ->setAddClassToListItem(true)
    ->setLiActiveClass('active');
?>

<nav class="navbar fixed-top navbar-expand-lg navbar-dark elegant-color scrolling-navbar">
    <a class="navbar-brand" href="#"><strong>Navbar</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <?= $menu->render(); ?>

        <ul class="navbar-nav nav-flex-icons">
            <li class="nav-item">
                <a class="nav-link"><i class="fa fa-facebook"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link"><i class="fa fa-twitter"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link"><i class="fa fa-instagram"></i></a>
            </li>
        </ul>
    </div>
</nav>
